name: Check and Create PR for reference.md changes

on:
  schedule:
    - cron: '0 4 * * *'  # This triggers the workflow every day at 4 AM UTC

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get today's date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Check for Changes in reference.md
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: 'gtfs/spec/en/reference.md'
          token: ${{ secrets.GTFS_VALIDATOR_CHECK_REFERENCE_MD_UPDATES }}
          repository: google/transit
          ref: master
          ignore-whitespace: true
      
      - name: Create Pull Request
        if: steps.changed-files.outputs.files-changed > 0
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GTFS_VALIDATOR_CHECK_REFERENCE_MD_UPDATES }}
          commit-message: "Changes made to `reference.md` from Google Transit's repo"
          title: "Changes made to `reference.md` from Google Transit's repo"
          body: "Commits have been made to the `reference.md` file in the last 24 hours. Automatically generated pull request."
          branch: "reference-md-commits-${{ steps.date.outputs.date }}"
          base: "master"
          labels: "automated-pr"

          files: |
            gtfs/spec/en/reference.md
            
          reviewers: emmambd
          assignees: emmambd
